//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDChat.ServicioRegistro {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioRegistro.RegistroSoap")]
    public interface RegistroSoap {
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UsuarioRegistro", ReplyAction="*")]
        SDChat.ServicioRegistro.UsuarioRegistroResponse UsuarioRegistro(SDChat.ServicioRegistro.UsuarioRegistroRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsuarioRegistroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsuarioRegistro", Namespace="http://tempuri.org/", Order=0)]
        public SDChat.ServicioRegistro.UsuarioRegistroRequestBody Body;
        
        public UsuarioRegistroRequest() {
        }
        
        public UsuarioRegistroRequest(SDChat.ServicioRegistro.UsuarioRegistroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UsuarioRegistroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string confirmacion;
        
        public UsuarioRegistroRequestBody() {
        }
        
        public UsuarioRegistroRequestBody(string nombre, string contrasena, string confirmacion) {
            this.nombre = nombre;
            this.contrasena = contrasena;
            this.confirmacion = confirmacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsuarioRegistroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsuarioRegistroResponse", Namespace="http://tempuri.org/", Order=0)]
        public SDChat.ServicioRegistro.UsuarioRegistroResponseBody Body;
        
        public UsuarioRegistroResponse() {
        }
        
        public UsuarioRegistroResponse(SDChat.ServicioRegistro.UsuarioRegistroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UsuarioRegistroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UsuarioRegistroResult;
        
        public UsuarioRegistroResponseBody() {
        }
        
        public UsuarioRegistroResponseBody(int UsuarioRegistroResult) {
            this.UsuarioRegistroResult = UsuarioRegistroResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegistroSoapChannel : SDChat.ServicioRegistro.RegistroSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistroSoapClient : System.ServiceModel.ClientBase<SDChat.ServicioRegistro.RegistroSoap>, SDChat.ServicioRegistro.RegistroSoap {
        
        public RegistroSoapClient() {
        }
        
        public RegistroSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistroSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistroSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistroSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SDChat.ServicioRegistro.UsuarioRegistroResponse SDChat.ServicioRegistro.RegistroSoap.UsuarioRegistro(SDChat.ServicioRegistro.UsuarioRegistroRequest request) {
            return base.Channel.UsuarioRegistro(request);
        }
        
        public int UsuarioRegistro(string nombre, string contrasena, string confirmacion) {
            SDChat.ServicioRegistro.UsuarioRegistroRequest inValue = new SDChat.ServicioRegistro.UsuarioRegistroRequest();
            inValue.Body = new SDChat.ServicioRegistro.UsuarioRegistroRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.contrasena = contrasena;
            inValue.Body.confirmacion = confirmacion;
            SDChat.ServicioRegistro.UsuarioRegistroResponse retVal = ((SDChat.ServicioRegistro.RegistroSoap)(this)).UsuarioRegistro(inValue);
            return retVal.Body.UsuarioRegistroResult;
        }
    }
}
