//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDChat.ServicioLogin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioLogin.LoginSoap")]
    public interface LoginSoap {
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UsuarioLogin", ReplyAction="*")]
        SDChat.ServicioLogin.UsuarioLoginResponse UsuarioLogin(SDChat.ServicioLogin.UsuarioLoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsuarioLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsuarioLogin", Namespace="http://tempuri.org/", Order=0)]
        public SDChat.ServicioLogin.UsuarioLoginRequestBody Body;
        
        public UsuarioLoginRequest() {
        }
        
        public UsuarioLoginRequest(SDChat.ServicioLogin.UsuarioLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UsuarioLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        public UsuarioLoginRequestBody() {
        }
        
        public UsuarioLoginRequestBody(string usuario, string contrasena) {
            this.usuario = usuario;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsuarioLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsuarioLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public SDChat.ServicioLogin.UsuarioLoginResponseBody Body;
        
        public UsuarioLoginResponse() {
        }
        
        public UsuarioLoginResponse(SDChat.ServicioLogin.UsuarioLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UsuarioLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UsuarioLoginResult;
        
        public UsuarioLoginResponseBody() {
        }
        
        public UsuarioLoginResponseBody(int UsuarioLoginResult) {
            this.UsuarioLoginResult = UsuarioLoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginSoapChannel : SDChat.ServicioLogin.LoginSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginSoapClient : System.ServiceModel.ClientBase<SDChat.ServicioLogin.LoginSoap>, SDChat.ServicioLogin.LoginSoap {
        
        public LoginSoapClient() {
        }
        
        public LoginSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SDChat.ServicioLogin.UsuarioLoginResponse SDChat.ServicioLogin.LoginSoap.UsuarioLogin(SDChat.ServicioLogin.UsuarioLoginRequest request) {
            return base.Channel.UsuarioLogin(request);
        }
        
        public int UsuarioLogin(string usuario, string contrasena) {
            SDChat.ServicioLogin.UsuarioLoginRequest inValue = new SDChat.ServicioLogin.UsuarioLoginRequest();
            inValue.Body = new SDChat.ServicioLogin.UsuarioLoginRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            SDChat.ServicioLogin.UsuarioLoginResponse retVal = ((SDChat.ServicioLogin.LoginSoap)(this)).UsuarioLogin(inValue);
            return retVal.Body.UsuarioLoginResult;
        }
    }
}
